name: invoice_app_new
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.6.0
  crypto: ^3.0.3
  ffi: ^2.1.2
  file: ^6.1.2
  file_selector_platform_interface: ^2.6.2
  flutter_plugin_android_lifecycle: ^2.0.19
  http: ^1.2.1
  http_parser: ^4.0.2
  image: ^4.2.0
  image_picker: ^1.1.1
  image_picker_android: ^0.8.1
  image_picker_for_web: ^3.0.4
  image_picker_ios: ^0.8.11+2
  image_picker_platform_interface: ^2.10.0
  js: ^0.7.1
  material_color_utilities: ^0.8.0
  meta: ^1.12.0
  mime: ^1.0.5
  open_file: ^3.3.2
  path_parsing: ^1.0.1
  path_provider: ^2.1.3
  path_provider_android: ^2.2.4
  path_provider_linux: ^2.2.1
  path_provider_macos: ^2.0.7
  path_provider_platform_interface: ^2.1.2
  path_provider_windows: ^2.2.1
  platform: ^3.1.4
  plugin_platform_interface: ^2.1.8
  process: ^5.0.2
  share_plus: ^2.0.0
  share_plus_platform_interface: ^2.0.0
  test_api: ^0.7.0
  typed_data: ^1.3.2
  url_launcher: ^6.2.6
  url_launcher_android: ^6.3.2
  url_launcher_ios: ^6.3.0
  url_launcher_linux: ^3.1.1
  url_launcher_macos: ^3.2.0
  url_launcher_platform_interface: ^2.3.2
  url_launcher_web: ^2.3.1
  url_launcher_windows: ^3.1.1
  uuid: ^4.4.0
  vm_service: ^14.2.1
  win32: ^5.5.1
  xdg_directories: ^1.0.4
  pdf: ^3.10.8
  printing: ^5.9.1
  get: ^4.6.6
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
